<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: descriptor.proto

namespace Google\Protobuf;

if (false) {
    /**
     * This class is deprecated. Use Google\Protobuf\DescriptorProto\ReservedRange instead.
     * @deprecated
     */
    class DescriptorProto_ReservedRange {}
}
class_exists(DescriptorProto\ReservedRange::class);
@trigger_error('Google\Protobuf\DescriptorProto_ReservedRange is deprecated and will be removed in the next major release. Use Google\Protobuf\DescriptorProto\ReservedRange instead', E_USER_DEPRECATED);

