<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: descriptor.proto

namespace Google\Protobuf;

if (false) {
    /**
     * This class is deprecated. Use Google\Protobuf\DescriptorProto\ExtensionRange instead.
     * @deprecated
     */
    class DescriptorProto_ExtensionRange {}
}
class_exists(DescriptorProto\ExtensionRange::class);
@trigger_error('Google\Protobuf\DescriptorProto_ExtensionRange is deprecated and will be removed in the next major release. Use Google\Protobuf\DescriptorProto\ExtensionRange instead', E_USER_DEPRECATED);

