<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: descriptor.proto

namespace Google\Protobuf;

if (false) {
    /**
     * This class is deprecated. Use Google\Protobuf\FieldOptions\OptionRetention instead.
     * @deprecated
     */
    class FieldOptions_OptionRetention {}
}
class_exists(FieldOptions\OptionRetention::class);
@trigger_error('Google\Protobuf\FieldOptions_OptionRetention is deprecated and will be removed in the next major release. Use Google\Protobuf\FieldOptions\OptionRetention instead', E_USER_DEPRECATED);

