<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: descriptor.proto

namespace Google\Protobuf;

if (false) {
    /**
     * This class is deprecated. Use Google\Protobuf\FieldOptions\OptionTargetType instead.
     * @deprecated
     */
    class FieldOptions_OptionTargetType {}
}
class_exists(FieldOptions\OptionTargetType::class);
@trigger_error('Google\Protobuf\FieldOptions_OptionTargetType is deprecated and will be removed in the next major release. Use Google\Protobuf\FieldOptions\OptionTargetType instead', E_USER_DEPRECATED);

