<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: descriptor.proto

namespace Google\Protobuf;

if (false) {
    /**
     * This class is deprecated. Use Google\Protobuf\FieldDescriptorProto\Label instead.
     * @deprecated
     */
    class FieldDescriptorProto_Label {}
}
class_exists(FieldDescriptorProto\Label::class);
@trigger_error('Google\Protobuf\FieldDescriptorProto_Label is deprecated and will be removed in the next major release. Use Google\Protobuf\FieldDescriptorProto\Label instead', E_USER_DEPRECATED);

