<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: descriptor.proto

namespace Google\Protobuf;

if (false) {
    /**
     * This class is deprecated. Use Google\Protobuf\FieldOptions\CType instead.
     * @deprecated
     */
    class FieldOptions_CType {}
}
class_exists(FieldOptions\CType::class);
@trigger_error('Google\Protobuf\FieldOptions_CType is deprecated and will be removed in the next major release. Use Google\Protobuf\FieldOptions\CType instead', E_USER_DEPRECATED);

