<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: descriptor.proto

namespace Google\Protobuf;

if (false) {
    /**
     * This class is deprecated. Use Google\Protobuf\FieldOptions\JSType instead.
     * @deprecated
     */
    class FieldOptions_JSType {}
}
class_exists(FieldOptions\JSType::class);
@trigger_error('Google\Protobuf\FieldOptions_JSType is deprecated and will be removed in the next major release. Use Google\Protobuf\FieldOptions\JSType instead', E_USER_DEPRECATED);

