<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: descriptor.proto

namespace Google\Protobuf;

if (false) {
    /**
     * This class is deprecated. Use Google\Protobuf\GeneratedCodeInfo\Annotation instead.
     * @deprecated
     */
    class GeneratedCodeInfo_Annotation {}
}
class_exists(GeneratedCodeInfo\Annotation::class);
@trigger_error('Google\Protobuf\GeneratedCodeInfo_Annotation is deprecated and will be removed in the next major release. Use Google\Protobuf\GeneratedCodeInfo\Annotation instead', E_USER_DEPRECATED);

