<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: descriptor.proto

namespace Google\Protobuf;

if (false) {
    /**
     * This class is deprecated. Use Google\Protobuf\MethodOptions\IdempotencyLevel instead.
     * @deprecated
     */
    class MethodOptions_IdempotencyLevel {}
}
class_exists(MethodOptions\IdempotencyLevel::class);
@trigger_error('Google\Protobuf\MethodOptions_IdempotencyLevel is deprecated and will be removed in the next major release. Use Google\Protobuf\MethodOptions\IdempotencyLevel instead', E_USER_DEPRECATED);

