<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: descriptor.proto

namespace Google\Protobuf;

if (false) {
    /**
     * This class is deprecated. Use Google\Protobuf\SourceCodeInfo\Location instead.
     * @deprecated
     */
    class SourceCodeInfo_Location {}
}
class_exists(SourceCodeInfo\Location::class);
@trigger_error('Google\Protobuf\SourceCodeInfo_Location is deprecated and will be removed in the next major release. Use Google\Protobuf\SourceCodeInfo\Location instead', E_USER_DEPRECATED);

