<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: descriptor.proto

namespace Google\Protobuf;

if (false) {
    /**
     * This class is deprecated. Use Google\Protobuf\UninterpretedOption\NamePart instead.
     * @deprecated
     */
    class UninterpretedOption_NamePart {}
}
class_exists(UninterpretedOption\NamePart::class);
@trigger_error('Google\Protobuf\UninterpretedOption_NamePart is deprecated and will be removed in the next major release. Use Google\Protobuf\UninterpretedOption\NamePart instead', E_USER_DEPRECATED);

