name: Build ROC Generator

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  php:
    name: Build PHP
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        php-version: [ '8.1' ]
        arch: [ 'macos.arm', 'macos.x86_64', 'linux.musl.aarch64', 'linux.musl.x86_64', 'linux.glibc.x86_64', 'windows.x86_64' ]
        fail-fast: false
      max-parallel: 5
    env:
      PHP_VERSION: ${{ matrix.php-version }}
      GH_TOKEN: ${{ github.token }}
      ARCH: ${{ matrix.arch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: phpize
          ini-values: opcache.enable_cli=0
          coverage: none
          extensions: pdo, pdo_mysql, redis
      - name: Setup Packages
        run: |
          cd php
          composer install -o --no-dev
      - name: Fetch the micro artifacts id
        id: fetch-micro-artifacts-id
        run: php .github/workflows/fetch_micro_artifacts_id.php
      - name: Build Artifacts
        run: |
          # Build phar
          cd php
          php -dphar.readonly=Off main.php phar:build -b main.php --name roc.phar
          gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/dixyes/lwmbs/actions/artifacts/${{ steps.fetch-micro-artifacts-id.outputs.id }}/zip > micro.zip
          unzip micro.zip
          cat micro.sfx roc.phar > roc-php
          chmod u+x roc-php
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: roc-php_${{ matrix.php-version }}_${{ matrix.arch }}
          path: |
            php/roc-php
